[16/Dec/2013 21:27:05] WARNING [django.request:177] Forbidden (CSRF cookie not set.): /users/sign_up/
[16/Dec/2013 21:27:12] ERROR [django.request:212] Internal Server Error: /users/sign_up/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/www/evolucion/evolucion/users/views.py", line 63, in sign_up
    return HttpResponse(serializers.serialize("xml", users),
NameError: global name 'users' is not defined
[16/Dec/2013 21:27:43] ERROR [django.request:212] Internal Server Error: /users/sign_up/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/www/evolucion/evolucion/users/views.py", line 63, in sign_up
    return HttpResponse(serializers.serialize("xml", form_errors),
  File "/usr/local/lib/python2.7/dist-packages/django/core/serializers/__init__.py", line 99, in serialize
    s.serialize(queryset, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/serializers/base.py", line 43, in serialize
    self.start_object(obj)
  File "/usr/local/lib/python2.7/dist-packages/django/core/serializers/xml_serializer.py", line 46, in start_object
    raise base.SerializationError("Non-model object (%s) encountered during serialization" % type(obj))
SerializationError: Non-model object (<type 'str'>) encountered during serialization
[16/Dec/2013 21:38:05] WARNING [django.request:177] Forbidden (CSRF cookie not set.): /users/sign_up/
[16/Dec/2013 21:38:09] WARNING [django.request:177] Forbidden (CSRF cookie not set.): /users/sign_up/
[16/Dec/2013 21:38:10] WARNING [django.request:177] Forbidden (CSRF cookie not set.): /users/sign_up/
[16/Dec/2013 22:00:41] WARNING [django.request:177] Forbidden (CSRF cookie not set.): /users/sign_up/
[16/Dec/2013 22:01:44] DEBUG [django.db.backends:51] (0.004) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."username" = 'johntalent'  LIMIT 1; args=(u'johntalent',)
[16/Dec/2013 22:01:44] DEBUG [django.db.backends:51] (0.001) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."email" = 'john@gmail.com'  LIMIT 1; args=(u'john@gmail.com',)
[16/Dec/2013 22:02:34] DEBUG [django.db.backends:51] (0.003) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."username" = 'johntalent'  LIMIT 1; args=(u'johntalent',)
[16/Dec/2013 22:02:34] DEBUG [django.db.backends:51] (0.001) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."email" = 'john@gmail.com'  LIMIT 1; args=(u'john@gmail.com',)
[16/Dec/2013 22:02:43] DEBUG [django.db.backends:51] (0.003) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."username" = 'johntalent'  LIMIT 1; args=(u'johntalent',)
[16/Dec/2013 22:02:43] DEBUG [django.db.backends:51] (0.001) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."email" = 'john@gmail.com'  LIMIT 1; args=(u'john@gmail.com',)
[16/Dec/2013 22:02:49] DEBUG [django.db.backends:51] (0.005) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."username" = 'johntalent'  LIMIT 1; args=(u'johntalent',)
[16/Dec/2013 22:02:49] DEBUG [django.db.backends:51] (0.001) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."email" = 'john@gmail.com'  LIMIT 1; args=(u'john@gmail.com',)
[16/Dec/2013 22:02:55] DEBUG [django.db.backends:51] (0.002) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."username" = 'johntalent'  LIMIT 1; args=(u'johntalent',)
[16/Dec/2013 22:02:55] DEBUG [django.db.backends:51] (0.001) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."email" = 'john@gmail.com'  LIMIT 1; args=(u'john@gmail.com',)
[16/Dec/2013 22:03:06] DEBUG [django.db.backends:51] (0.002) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."username" = 'johntalent1'  LIMIT 1; args=(u'johntalent1',)
[16/Dec/2013 22:03:06] DEBUG [django.db.backends:51] (0.001) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."email" = 'john@gmail.com'  LIMIT 1; args=(u'john@gmail.com',)
[16/Dec/2013 22:03:06] DEBUG [django.db.backends:51] (0.113) INSERT INTO "users_user" ("first_name", "last_name", "username", "email", "password", "accept_terms", "last_login", "created_at", "updated_at") VALUES ('Jhon Freddy', 'Garavito Su√°rez', 'johntalent1', 'john@gmail.com', 'iNNOVAR01', true, '2013-12-16 22:03:06.424376-05:00', '2013-12-16 22:03:06.424294-05:00', '2013-12-16 22:03:06.424353-05:00') RETURNING "users_user"."id"; args=(u'Jhon Freddy', u'Garavito Su\xe1rez', u'johntalent1', u'john@gmail.com', u'iNNOVAR01', True, u'2013-12-16 22:03:06.424376-05:00', u'2013-12-16 22:03:06.424294-05:00', u'2013-12-16 22:03:06.424353-05:00')
[16/Dec/2013 22:03:06] ERROR [django.request:212] Internal Server Error: /users/sign_up/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/www/evolucion/evolucion/utils/decorators.py", line 33, in vista
    'response': res
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <django.http.response.HttpResponse object at 0x7ff76c079990> is not JSON serializable
[17/Dec/2013 03:56:07] DEBUG [django.db.backends:51] (0.206) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1 ; args=(1,)
[17/Dec/2013 03:59:18] DEBUG [django.db.backends:51] (0.003) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1 ; args=(1,)
[17/Dec/2013 03:59:18] ERROR [django.request:212] Internal Server Error: /users/get_json/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/www/evolucion/evolucion/utils/decorators.py", line 33, in vista
    'response': res
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <django.http.response.HttpResponse object at 0x7fd32c4ce990> is not JSON serializable
[17/Dec/2013 03:59:57] DEBUG [django.db.backends:51] (0.002) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1 ; args=(1,)
[17/Dec/2013 03:59:57] ERROR [django.request:212] Internal Server Error: /users/get_json/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/www/evolucion/evolucion/utils/decorators.py", line 33, in vista
    'response': res
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <django.http.response.HttpResponse object at 0x7f0c2407b5d0> is not JSON serializable
[17/Dec/2013 04:02:04] DEBUG [django.db.backends:51] (0.001) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1 ; args=(1,)
[17/Dec/2013 04:02:04] ERROR [django.request:212] Internal Server Error: /users/get_json/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/www/evolucion/evolucion/utils/decorators.py", line 33, in vista
    'response': res
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <django.http.response.HttpResponse object at 0x7f93c84cd990> is not JSON serializable
[17/Dec/2013 04:02:20] DEBUG [django.db.backends:51] (0.002) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1 ; args=(1,)
[17/Dec/2013 04:02:20] ERROR [django.request:212] Internal Server Error: /users/get_json/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/www/evolucion/evolucion/utils/decorators.py", line 33, in vista
    'response': res
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <django.http.response.HttpResponse object at 0x7f32344e86d0> is not JSON serializable
[17/Dec/2013 04:03:34] WARNING [django.request:146] Not Found: /users/get_htlml/
[17/Dec/2013 04:03:55] WARNING [django.request:146] Not Found: /users/get_html/
[17/Dec/2013 04:16:52] ERROR [django.request:212] Internal Server Error: /users/sign_up/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/www/evolucion/evolucion/utils/decorators.py", line 33, in vista
    'response': res
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <django.http.response.HttpResponse object at 0x7fd6104d2f10> is not JSON serializable
[17/Dec/2013 04:17:00] ERROR [django.request:212] Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/www/evolucion/evolucion/views.py", line 10, in home
    return render(request, 'home/index.html', context)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 177, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 102, in render
    compiled_parent = self.get_parent(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 99, in get_parent
    return get_template(parent)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 135, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 157, in get_template_from_string
    return Template(source, origin, name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 215, in do_extends
    nodelist = parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 263, in do_include
    isolated_context=isolated_context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 146, in __init__
    t = get_template(template_path)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 135, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 157, in get_template_from_string
    return Template(source, origin, name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 263, in do_include
    isolated_context=isolated_context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 146, in __init__
    t = get_template(template_path)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 135, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 157, in get_template_from_string
    return Template(source, origin, name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 905, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 769, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 272, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 327, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'trans', expected 'empty' o 'endfor'
[17/Dec/2013 04:17:01] WARNING [django.request:146] Not Found: /favicon.ico
[17/Dec/2013 04:17:33] ERROR [django.request:212] Internal Server Error: /users/sign_up/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/www/evolucion/evolucion/utils/decorators.py", line 33, in vista
    'response': res
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <django.http.response.HttpResponse object at 0x7fd60005d810> is not JSON serializable
[17/Dec/2013 04:23:03] DEBUG [django.db.backends:51] (0.163) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."username" = 'johntalent'  LIMIT 1; args=(u'johntalent',)
[17/Dec/2013 04:25:06] DEBUG [django.db.backends:51] (0.004) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."username" = 'johntalent2'  LIMIT 1; args=(u'johntalent2',)
[17/Dec/2013 04:25:13] DEBUG [django.db.backends:51] (0.004) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."username" = 'johntalent2'  LIMIT 1; args=(u'johntalent2',)
[17/Dec/2013 04:25:23] DEBUG [django.db.backends:51] (0.002) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."username" = 'johntalent2'  LIMIT 1; args=(u'johntalent2',)
[17/Dec/2013 04:25:32] DEBUG [django.db.backends:51] (0.002) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."username" = 'johntalent2'  LIMIT 1; args=(u'johntalent2',)
[17/Dec/2013 04:25:32] DEBUG [django.db.backends:51] (0.047) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."email" = 'john@talent.com'  LIMIT 1; args=(u'john@talent.com',)
[17/Dec/2013 04:25:43] DEBUG [django.db.backends:51] (0.002) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."username" = 'johntalent2'  LIMIT 1; args=(u'johntalent2',)
[17/Dec/2013 04:25:43] DEBUG [django.db.backends:51] (0.000) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."email" = 'john@talent.com'  LIMIT 1; args=(u'john@talent.com',)
[17/Dec/2013 04:25:44] DEBUG [django.db.backends:51] (0.115) INSERT INTO "users_user" ("first_name", "last_name", "username", "email", "password", "accept_terms", "last_login", "created_at", "updated_at") VALUES ('John Freddy', 'Garavito Su√°rez', 'johntalent2', 'john@talent.com', 'Innovar01', true, '2013-12-17 04:25:43.911942-05:00', '2013-12-17 04:25:43.911872-05:00', '2013-12-17 04:25:43.911926-05:00') RETURNING "users_user"."id"; args=(u'John Freddy', u'Garavito Su\xe1rez', u'johntalent2', u'john@talent.com', u'Innovar01', True, u'2013-12-17 04:25:43.911942-05:00', u'2013-12-17 04:25:43.911872-05:00', u'2013-12-17 04:25:43.911926-05:00')
[17/Dec/2013 04:25:44] WARNING [django.request:146] Not Found: /jquery-1.10.2.min.map
[17/Dec/2013 04:54:04] DEBUG [django.db.backends:51] (0.173) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."username" = 'johntalent01'  LIMIT 1; args=(u'johntalent01',)
[17/Dec/2013 04:54:04] DEBUG [django.db.backends:51] (0.022) SELECT (1) AS "a" FROM "users_user" WHERE "users_user"."email" = 'talent.corp@gmail.com'  LIMIT 1; args=(u'talent.corp@gmail.com',)
[17/Dec/2013 04:54:04] DEBUG [django.db.backends:51] (0.052) INSERT INTO "users_user" ("first_name", "last_name", "username", "email", "password", "accept_terms", "last_login", "created_at", "updated_at") VALUES ('John Freddy', 'Garavito Su√°rez', 'johntalent01', 'talent.corp@gmail.com', 'Innovar01', true, '2013-12-17 04:54:03.727442-05:00', '2013-12-17 04:54:03.727337-05:00', '2013-12-17 04:54:03.727411-05:00') RETURNING "users_user"."id"; args=(u'John Freddy', u'Garavito Su\xe1rez', u'johntalent01', u'talent.corp@gmail.com', u'Innovar01', True, u'2013-12-17 04:54:03.727442-05:00', u'2013-12-17 04:54:03.727337-05:00', u'2013-12-17 04:54:03.727411-05:00')
